### ISSUE TITLE
Error on running the agent

### ISSUE THREAD

**Issue by fajrulfx** [openai/Video-Pre-Training#16]
I got these errors when running the agent. Not sure why this happened, because previously, the program worked fine.
```
D:\Data\Documents\minecraft-vpt>python run_agent.py --model foundation-model-3x.model --weights foundation-model-3x.weights
---Loading model---
---Launching MineRL enviroment (be patient)---
C:\Users\Fajrul\AppData\Local\Programs\Python\Python39\lib\runpy.py:127: RuntimeWarning: 'minerl.utils.process_watcher' found in sys.modules 
after import of package 'minerl.utils', but prior to execution of 'minerl.utils.process_watcher'; this may result in unpredictable behaviour 
  warn(RuntimeWarning(msg))
C:\Users\Fajrul\AppData\Local\Programs\Python\Python39\lib\runpy.py:127: RuntimeWarning: 'daemoniker._daemonize_windows' found in sys.modules after import of package 'daemoniker', but prior to execution of 'daemoniker._daemonize_windows'; this may result in unpredictable behaviour 
  warn(RuntimeWarning(msg))
Traceback (most recent call last):
  File "D:\Data\Documents\minecraft-vpt\run_agent.py", line 35, in <module>
    main(args.model, args.weights)
  File "D:\Data\Documents\minecraft-vpt\run_agent.py", line 19, in main
    obs = env.reset()
  File "C:\Users\Fajrul\AppData\Local\Programs\Python\Python39\lib\site-packages\minerl\env\_singleagent.py", line 22, in reset
    multi_obs = super().reset()
  File "C:\Users\Fajrul\AppData\Local\Programs\Python\Python39\lib\site-packages\minerl\env\_multiagent.py", line 446, in reset
    self._send_mission(self.instances[0], agent_xmls[0], self._get_token(0, ep_uid))  # Master
  File "C:\Users\Fajrul\AppData\Local\Programs\Python\Python39\lib\site-packages\minerl\env\_multiagent.py", line 606, in _send_mission      
    ok, = struct.unpack("!I", reply)
```
I remember that the RuntimeWarning was there previously when I successfully ran the code. However, the rest of the error is new. What's the possible cause of this? Thank you.

**Comment by Miffyli** [comment]
That is an error stemming from the MineRL environment. I recommend enabling logging to see logs from Minecraft side to see what could be wrong. Add this to the top of `run_agent.py` to see the logs:

```
import logging
logging.basicConfig(level=logging.DEBUG)
```

**Comment by fajrulfx** [comment]
Here's the log. Could you explain the possible way to fix this?
```
DEBUG:minerl.env.malmo.instance.7582ea:SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
DEBUG:minerl.env.malmo.instance.7582ea:SLF4J: Defaulting to no-operation (NOP) logger implementation
DEBUG:minerl.env.malmo.instance.7582ea:SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
DEBUG:minerl.env.malmo.instance.7582ea:[12:44:12] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'       
ERROR:minerl.env.malmo.instance.7582ea:[12:44:13] [Render thread/ERROR]: Failed to verify authentication!
DEBUG:minerl.env.malmo.instance.7582ea:[12:44:13] [Render thread/INFO]: Setting user: Player259
DEBUG:minerl.env.malmo.instance.7582ea:[12:44:13] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 SNAPSHOT
ERROR:minerl.env.malmo.instance.7582ea:[12:44:14] [Render thread/WARN]: ERROR : Couldn't load Narrator library : Unable to load library 'SAPIWrapper_x64': Can't obtain InputStream for win32-x86-64/SAPIWrapper_x64.dll
ERROR:minerl.env.malmo.instance.7582ea:ERROR : Couldn't load Narrator library : Unable to load library 'SAPIWrapper_x86': Can't obtain InputStream for win32-x86-64/SAPIWrapper_x86.dll
DEBUG:minerl.env.malmo.instance.7582ea:
DEBUG:minerl.env.malmo.instance.7582ea:[12:44:14] [Render thread/INFO]: Reloading ResourceManager: Default
DEBUG:minerl.env.malmo.instance.7582ea:[12:44:15] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms 
server: Invalid session id
DEBUG:minerl.env.malmo.instance.7582ea:[12:44:18] [Render thread/INFO]: OpenAL initialized.
DEBUG:minerl.env.malmo.instance.7582ea:[12:44:18] [Render thread/INFO]: Sound engine started
DEBUG:minerl.env.malmo.instance.7582ea:[12:44:18] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
DEBUG:minerl.env.malmo.instance.7582ea:[12:44:18] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
DEBUG:minerl.env.malmo.instance.7582ea:[12:44:18] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
DEBUG:minerl.env.malmo.instance.7582ea:[12:44:18] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
DEBUG:minerl.env.malmo.instance.7582ea:[12:44:18] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
DEBUG:minerl.env.malmo.instance.7582ea:[12:44:18] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
DEBUG:minerl.env.malmo.instance.7582ea:[12:44:18] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas  
DEBUG:minerl.env.malmo.instance.7582ea:[12:44:19] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
DEBUG:minerl.env.malmo.instance.7582ea:[12:44:19] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
DEBUG:minerl.env.malmo.instance.7582ea:[12:44:19] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas    
DEBUG:minerl.env.malmo.instance.7582ea:[12:44:20] [Thread-4/INFO]: [STDOUT]: ***** Start MalmoEnvServer on port 11882
DEBUG:minerl.env.malmo.instance.7582ea:[12:44:20] [Thread-4/INFO]: [STDOUT]: CLIENT enter state: DORMANT
INFO:minerl.env.malmo.instance.7582ea:Minecraft process ready
DEBUG:minerl.env._multiagent:Creating socket connection Malmo[None:7582ea, proc=15044, addr=localhost:11882, locked=True]
INFO:minerl.env.malmo:Logging output of Minecraft to .\logs\mc_2882.log
DEBUG:minerl.env.malmo.instance.7582ea:[12:44:20] [Thread-4/INFO]: [STDOUT]: SERVER enter state: DORMANT
DEBUG:minerl.env._multiagent:Saying hello for client: Malmo[None:7582ea, proc=15044, addr=localhost:11882, locked=True]
INFO:minerl.env._multiagent:Attempting to quit: Malmo[None:7582ea, proc=15044, addr=localhost:11882, locked=True]
DEBUG:minerl.env._multiagent:Sending mission init: Malmo[None:7582ea, proc=15044, addr=localhost:11882, locked=True]
DEBUG:minerl.env.malmo.instance.7582ea:[12:44:20] [EnvServerSocketHandler/INFO]: Received Mission token 73d5443f-bdf7-4ec4-bbc5-0f69a59e60a3:0:0:1:true
DEBUG:minerl.env.malmo.instance.7582ea:[12:44:20] [EnvServerSocketHandler/INFO]: Received mission init command  <MissionInit xmlns="http://ProjectMalmo.microsoft.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" SchemaVersion="" PlatformVersion="0.37.0"><Mission><About><Summary>MineRLHumanSurvival-v0</Summary></About><ModSettings><MsPerTick>50</MsPerTick></ModSettings><ServerSection><ServerInitialConditions><Time><AllowPassageOfTime>true</AllowPassageOfTime></Time><AllowSpawning>true</AllowSpawning></ServerInitialConditions><ServerHandlers><DefaultWorldGenerator forceReset="true" generatorOptions="{}"/><ServerQuitWhenAnyAgentFinishes/></ServerHandlers></ServerSection><AgentSection mode="Survival"><Name>MineRLAgent0</Name><AgentStart><LowLevelInputs>true</LowLevelInputs><GuiScale>1.0</GuiScale><GammaSetting>2.0</GammaSetting><FOVSetting>70.0</FOVSetting><FakeCursorSize>16</FakeCursorSize></AgentStart><AgentHandlers><FileBasedPerformanceProducer/><PauseCommand/><VideoProducer want_depth="false"><Width>640</Width><Height>360</Height></VideoProducer><ObservationFromFullInventory flat="false"/><ObservationFromEquippedItem/><ObservationFromFullStats/><ObservationFromFullStats/><HumanLevelCommands/><CameraCommands/><IsGuiOpen/></AgentHandlers></AgentSection></Mission><ExperimentUID>73d5443f-bdf7-4ec4-bbc5-0f69a59e60a3</ExperimentUID><ClientRole>0</ClientRole><ClientAgentConnection><ClientIPAddress>127.0.0.1</ClientIPAddress><ClientMissionControlPort>0</ClientMissionControlPort><ClientCommandsPort>0</ClientCommandsPort><AgentIPAddress>127.0.0.1</AgentIPAddress><AgentMissionControlPort>0</AgentMissionControlPort><AgentVideoPort>0</AgentVideoPort><AgentDepthPort>0</AgentDepthPort><AgentLuminancePort>0</AgentLuminancePort><AgentObservationsPort>0</AgentObservationsPort><AgentRewardsPort>0</AgentRewardsPort><AgentColourMapPort>0</AgentColourMapPort></ClientAgentConnection></MissionInit>
ERROR:minerl.env.malmo.instance.7582ea:Exception in thread "EnvServerSocketHandler" [12:44:20] [EnvServerSocketHandler/INFO]: [STDERR]: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
ERROR:minerl.env.malmo.instance.7582ea:[12:44:20] [EnvServerSocketHandler/INFO]: [STDERR]:      at com.minerl.multiagent.env.EnvServer.initMission(EnvServer.java:234)
ERROR:minerl.env.malmo.instance.7582ea:[12:44:20] [EnvServerSocketHandler/INFO]: [STDERR]:      at com.minerl.multiagent.env.EnvServer$1.run(EnvServer.java:129)
ERROR:minerl.env.malmo.instance.7582ea:[12:44:20] [EnvServerSocketHandler/INFO]: [STDERR]: Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
ERROR:minerl.env.malmo.instance.7582ea:[12:44:20] [EnvServerSocketHandler/INFO]: [STDERR]:      at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
ERROR:minerl.env.malmo.instance.7582ea:[12:44:20] [EnvServerSocketHandler/INFO]: [STDERR]:      at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
ERROR:minerl.env.malmo.instance.7582ea:[12:44:20] [EnvServerSocketHandler/INFO]: [STDERR]:      at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
ERROR:minerl.env.malmo.instance.7582ea:[12:44:20] [EnvServerSocketHandler/INFO]: [STDERR]:      ... 2 more

Traceback (most recent call last):
  File "D:\Data\Documents\minecraft-vpt\run_agent.py", line 37, in <module>
    main(args.model, args.weights)
  File "D:\Data\Documents\minecraft-vpt\run_agent.py", line 21, in main
    obs = env.reset()
  File "C:\Users\Fajrul\AppData\Local\Programs\Python\Python39\lib\site-packages\minerl\env\_singleagent.py", line 22, in reset
    multi_obs = super().reset()
  File "C:\Users\Fajrul\AppData\Local\Programs\Python\Python39\lib\site-packages\minerl\env\_multiagent.py", line 446, in reset
    self._send_mission(self.instances[0], agent_xmls[0], self._get_token(0, ep_uid))  # Master
  File "C:\Users\Fajrul\AppData\Local\Programs\Python\Python39\lib\site-packages\minerl\env\_multiagent.py", line 606, in _send_mission      
    ok, = struct.unpack("!I", reply)
TypeError: a bytes-like object is required, not 'NoneType'
DEBUG:minerl.env.malmo.instance.7582ea:[12:44:21] [Render thread/INFO]: [STDOUT]: *** creating fake mouse cursor ***
```

**Comment by Miffyli** [comment]
Oh, that is a new error... I do not have a good solution for this, to be honest :( . It might be importing MineRL from a wrong place or something was misplaced in the installation (for some reason). I would recommend reinstalling MineRL and trying again.

**Comment by fajrulfx** [comment]
I updated Java in PATH because it is overridden by ``C:\Program Files\Common Files\Oracle\Java\javapath`` which contains Java 17, then I reinstalled MineRL. 
The same error still occurred on my first run (foundation 1 model and weights). But after I change to another model and weights, now everything works. 

Another question, not sure if I should ask here. How can I increase the size of the window and framerate of the client? Thanks

**Comment by Miffyli** [comment]
Glad to hear you fixed it :). You can not change the settings of the Minecraft window: the framerate is at maximum by default (it is bit slow with the VPT model), and resolution has to be fixed for the right input size for the model.

**Comment by PeymanQuant** [comment]
@fajrulfx hello, I am receiving the exact error while trying to run en.reset() for the NavigateDense environment. Could you please say what exactly have you done, which fixed it? 
Thank you

**Comment by fajrulfx** [comment]
I vaguely remember it. I follow the solution from https://github.com/minerllabs/minerl/issues/636 for MineRL installation problem and update JAVA path as mentioned above.
