### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by jhsul** [openai/Video-Pre-Training#25]
**Environment:**
- Apple M2 Max
- conda python 3.9.16 environment
- numpy==1.23.5
- opencv-python==4.7.0.72
- Oracle java 8 x86_64 jdk running on rosetta, following from the steps [here](https://github.com/minerllabs/minerl/issues/659#issuecomment-1306635414)

I got this error after running the `run_agent` script as specified in the README:

```sh
python run_agent.py --model models/foundation-model-1x.model --weights weights/foundation-model-1x.weights
```

The output of this command is as follows:

```
---Loading model---
---Launching MineRL enviroment (be patient)---
/Users/jack/miniconda3/envs/vpt/lib/python3.9/runpy.py:127: RuntimeWarning: 'minerl.utils.process_watcher' found in sys.modules after import of package 'minerl.utils', but prior to execution of 'minerl.utils.process_watcher'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Traceback (most recent call last):
  File "/Users/jack/Documents/GitHub/Video-Pre-Training/run_agent.py", line 35, in <module>
    main(args.model, args.weights)
  File "/Users/jack/Documents/GitHub/Video-Pre-Training/run_agent.py", line 19, in main
    obs = env.reset()
  File "/Users/jack/miniconda3/envs/vpt/lib/python3.9/site-packages/minerl/env/_singleagent.py", line 22, in reset
    multi_obs = super().reset()
  File "/Users/jack/miniconda3/envs/vpt/lib/python3.9/site-packages/minerl/env/_multiagent.py", line 457, in reset
    return self._peek_obs()
  File "/Users/jack/miniconda3/envs/vpt/lib/python3.9/site-packages/minerl/env/_multiagent.py", line 641, in _peek_obs
    multi_obs[actor_name], _ = self._process_observation(actor_name, obs, info)
  File "/Users/jack/miniconda3/envs/vpt/lib/python3.9/site-packages/minerl/env/_multiagent.py", line 223, in _process_observation
    obs_dict[h.to_string()] = h.from_hero(info)
  File "/Users/jack/miniconda3/envs/vpt/lib/python3.9/site-packages/minerl/herobraine/hero/handlers/translation.py", line 122, in from_hero
    return {
  File "/Users/jack/miniconda3/envs/vpt/lib/python3.9/site-packages/minerl/herobraine/hero/handlers/translation.py", line 123, in <dictcomp>
    h.to_string(): h.from_hero(x)
  File "/Users/jack/miniconda3/envs/vpt/lib/python3.9/site-packages/minerl/herobraine/hero/handlers/translation.py", line 122, in from_hero
    return {
  File "/Users/jack/miniconda3/envs/vpt/lib/python3.9/site-packages/minerl/herobraine/hero/handlers/translation.py", line 123, in <dictcomp>
    h.to_string(): h.from_hero(x)
  File "/Users/jack/miniconda3/envs/vpt/lib/python3.9/site-packages/minerl/herobraine/hero/handlers/agent/observations/equipped_item.py", line 210, in from_hero
    return np.array(head[self.type_str])
TypeError: string indices must be integers
```

**Comment by jhsul** [comment]
My bad! This was because I botched my `minerl` installation by accident. Rebuilding it fixed everything.
