### ISSUE TITLE
gpu problem brand

### ISSUE THREAD

**Issue by Laz9999** [openai/Video-Pre-Training#32]
laz@DESKTOP-RQHN3N8:/mnt/c/Users/Laz/Desktop/Video-Pre-Training$ python3 run_agent.py --model 4x_idm.model --weights 4x_
idm.weights
---Loading model---
Traceback (most recent call last):
  File "/mnt/c/Users/Laz/Desktop/Video-Pre-Training/run_agent.py", line 35, in <module>
    main(args.model, args.weights)
  File "/mnt/c/Users/Laz/Desktop/Video-Pre-Training/run_agent.py", line 15, in main
    agent = MineRLAgent(env, policy_kwargs=policy_kwargs, pi_head_kwargs=pi_head_kwargs)
  File "/mnt/c/Users/Laz/Desktop/Video-Pre-Training/agent.py", line 128, in __init__
    self.policy = MinecraftAgentPolicy(**agent_kwargs).to(device)
  File "/home/laz/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/home/laz/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/laz/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/laz/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 4 more times]
  File "/home/laz/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/home/laz/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/home/laz/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
laz@DESKTOP-RQHN3N8:/mnt/c/Users/Laz/Desktop/Video-Pre-Training$

i want to ither use cpu or amd gpu

**Comment by Miffyli** [comment]
Running on AMD GPUs has not been tested. You can change the code to use CPU by modifying [this](https://github.com/openai/Video-Pre-Training/blob/4ea1e8e0eddcdd5ae3cc88621a80c434f22b7f3d/run_agent.py#L15C17-L15C17) line to:

```python
agent = MineRLAgent(env, policy_kwargs=policy_kwargs, pi_head_kwargs=pi_head_kwargs, device="cpu")
```
