### ISSUE TITLE
Unable to install MineRL

### ISSUE THREAD

**Issue by Emericen** [openai/Video-Pre-Training#43]
hey!!

huge fan of the project and would love to expand further and see if scales.

when i try to install minerl, i ran into this error:

```
(venv) eddy@RedBlackTree:~$ pip install git+https://github.com/minerllabs/minerl
Collecting git+https://github.com/minerllabs/minerl
  Cloning https://github.com/minerllabs/minerl to /tmp/pip-req-build-vo703r66
  Running command git clone --filter=blob:none --quiet https://github.com/minerllabs/minerl /tmp/pip-req-build-vo703r66
  Resolved https://github.com/minerllabs/minerl to commit 80a4673d90170e755fa95619c55d1ef3c7656bc4
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [160 lines of output]
      Cloning into 'MCP-Reborn'...
      Note: switching to '1.16.5-20210115'.

      You are in 'detached HEAD' state. You can look around, make experimental
      changes and commit them, and you can discard any commits you make in this
      state without impacting any branches by switching back to a branch.

      If you want to create a new branch to retain commits you create, you may
      do so (now or later) by using -c with the switch command. Example:

        git switch -c <new-branch-name>

      Or undo this operation with:

        git switch -

      Turn off this advice by setting config variable advice.detachedHead to false

      HEAD is now at 1e71be5 Update README.md
      Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
      > Task :mcp:downloadConfig

      > Task :mcp:setupMCP
      Setting up MCP environment
      Initializing steps
      Executing steps
       > Running 'downloadManifest'
       > Running 'downloadJson'
       > Running 'downloadClient'
       > Running 'downloadServer'
       > Running 'stripClient'
       > Running 'stripServer'
       > Running 'merge'
       > Running 'rename'
       > Running 'mcinject'
       > Running 'listLibraries'
       > Running 'decompile'
       > Running 'inject'
       > Running 'patch'
      MCP environment setup is complete

      > Task :applyPatches
      > Task :downloadMappings
      > Task :srg2mcp
      > Task :extractMapped
      > Task :setup

      BUILD SUCCESSFUL in 50s
      6 actionable tasks: 6 executed
      Starting a Gradle Daemon (subsequent builds will be faster)

      > Configure project :
      * * * * * * * * * * * * * * * * * * * * * * * *
      These are the repositories after plugins have been applied:
       | - MavenRepo -> https://repo.maven.apache.org/maven2/
       | - BintrayJCenter -> https://jcenter.bintray.com/
       | - maven -> https://repo.spongepowered.org/maven/
       | - maven2 -> https://maven.minecraftforge.net/
       | - BUNDELED_269204723 -> downloads to: /home/eddy/.gradle/caches/forge_gradle/bundeled_repo/
       | - maven3 -> https://libraries.minecraft.net/
      * * * * * * * * * * * * * * * * * * * * * * * *
      Repositories after removing proxied repos:
       | - MavenRepo -> https://repo.maven.apache.org/maven2/
       | - BintrayJCenter -> https://jcenter.bintray.com/
       | - maven -> https://repo.spongepowered.org/maven/
       | - maven2 -> https://maven.minecraftforge.net/
       | - BUNDELED_269204723 -> downloads to: /home/eddy/.gradle/caches/forge_gradle/bundeled_repo/
       | - maven3 -> https://libraries.minecraft.net/
      * * * * * * * * * * * * * * * * * * * * * * * *

      > Task :verifyRepos
      Checking BuildScript Repositories:
       | - [ OK ]: MavenLocal -> file:/home/eddy/.m2/repository
       | - [FAIL]: MavenRepo -> https://repo.maven.apache.org/maven2/
       | - [FAIL]: BintrayJCenter -> https://jcenter.bintray.com/
       | - [FAIL]: maven -> https://repo.spongepowered.org/maven/
      Checking Project Repositories:
       | - [FAIL]: MavenRepo -> https://repo.maven.apache.org/maven2/
       | - [FAIL]: BintrayJCenter -> https://jcenter.bintray.com/
       | - [FAIL]: maven -> https://repo.spongepowered.org/maven/
       | - [FAIL]: maven2 -> https://maven.minecraftforge.net/
       | - [ OK ]: BUNDELED_269204723 (accepted custom MC repo)
       | - [FAIL]: maven3 -> https://libraries.minecraft.net/

      > Task :downloadMCMeta
      > Task :downloadAssets

      Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
      Use '--warning-mode all' to show the individual deprecation warnings.
      See https://docs.gradle.org/6.8.1/userguide/command_line_interface.html#sec:command_line_warnings

      BUILD SUCCESSFUL in 10s
      3 actionable tasks: 3 executed

      > Configure project :
      * * * * * * * * * * * * * * * * * * * * * * * *
      These are the repositories after plugins have been applied:
       | - MavenRepo -> https://repo.maven.apache.org/maven2/
       | - BintrayJCenter -> https://jcenter.bintray.com/
       | - maven -> https://repo.spongepowered.org/maven/
       | - maven2 -> https://maven.minecraftforge.net/
       | - BUNDELED_-1950602590 -> downloads to: /home/eddy/.gradle/caches/forge_gradle/bundeled_repo/
       | - maven3 -> https://libraries.minecraft.net/
      * * * * * * * * * * * * * * * * * * * * * * * *
      Repositories after removing proxied repos:
       | - MavenRepo -> https://repo.maven.apache.org/maven2/
       | - BintrayJCenter -> https://jcenter.bintray.com/
       | - maven -> https://repo.spongepowered.org/maven/
       | - maven2 -> https://maven.minecraftforge.net/
       | - BUNDELED_-1950602590 -> downloads to: /home/eddy/.gradle/caches/forge_gradle/bundeled_repo/
       | - maven3 -> https://libraries.minecraft.net/
      * * * * * * * * * * * * * * * * * * * * * * * *

      > Task :verifyRepos
      Checking BuildScript Repositories:
       | - [ OK ]: MavenLocal -> file:/home/eddy/.m2/repository
       | - [FAIL]: MavenRepo -> https://repo.maven.apache.org/maven2/
       | - [FAIL]: BintrayJCenter -> https://jcenter.bintray.com/
       | - [FAIL]: maven -> https://repo.spongepowered.org/maven/
      Checking Project Repositories:
       | - [FAIL]: MavenRepo -> https://repo.maven.apache.org/maven2/
       | - [FAIL]: BintrayJCenter -> https://jcenter.bintray.com/
       | - [FAIL]: maven -> https://repo.spongepowered.org/maven/
       | - [FAIL]: maven2 -> https://maven.minecraftforge.net/
       | - [ OK ]: BUNDELED_-1950602590 (accepted custom MC repo)
       | - [FAIL]: maven3 -> https://libraries.minecraft.net/

      > Task :clean
      > Task :deleteSchemas
      > Task :copySchemas
      > Task :jaxb
      > Task :compileJava FAILED

      FAILURE: Build failed with an exception.

      * What went wrong:
      Execution failed for task ':compileJava'.
      > Could not find tools.jar. Please check that /usr/lib/jvm/java-8-openjdk-amd64 contains a valid JDK installation.

      * Try:
      Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

      * Get more help at https://help.gradle.org

      Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
      Use '--warning-mode all' to show the individual deprecation warnings.
      See https://docs.gradle.org/6.8.1/userguide/command_line_interface.html#sec:command_line_warnings

      BUILD FAILED in 9s
      6 actionable tasks: 6 executed
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-vo703r66/setup.py", line 223, in <module>
          prep_mcp()
        File "/tmp/pip-req-build-vo703r66/setup.py", line 207, in prep_mcp
          subprocess.check_call('{} clean build shadowJar'.format(gradlew).split(' '), cwd=workdir)
        File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['./gradlew', 'clean', 'build', 'shadowJar']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

any idea what this is? not too familiar w  `mcp-reborn`.

**Comment by Miffyli** [comment]
Hey. Installing on Mac requires additional steps. See this comment: https://github.com/minerllabs/minerl/issues/659#issuecomment-1306635414
