### ISSUE TITLE
Running pip install git+https://github.com/minerllabs/minerl@v1.0.0 gives error

### ISSUE THREAD

**Issue by Snowplou** [openai/Video-Pre-Training#7]
I get an error whenever I run
pip install git+https://github.com/minerllabs/minerl@v1.0.0

This is the error it gives:

Collecting git+https://github.com/minerllabs/minerl@v1.0.0
  Cloning https://github.com/minerllabs/minerl (to revision v1.0.0) to c:\users\john\appdata\local\temp\pip-req-build-iuu1d95z
  Running command git clone --filter=blob:none --quiet https://github.com/minerllabs/minerl 'C:\Users\john\AppData\Local\Temp\pip-req-build-iuu1d95z'
  Running command git checkout -b v1.0.0 --track origin/v1.0.0
  branch 'v1.0.0' set up to track 'origin/v1.0.0'.
  Switched to a new branch 'v1.0.0'
  Resolved https://github.com/minerllabs/minerl to commit aeb7c1b1a0cc8614ed8bd57e94c4614d1d04a12e
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\john\AppData\Local\Temp\pip-req-build-iuu1d95z\setup.py", line 203, in <module>
          prep_mcp()
        File "C:\Users\john\AppData\Local\Temp\pip-req-build-iuu1d95z\setup.py", line 136, in prep_mcp
          setup_output = subprocess.check_output(['bash.exe', 'setup_mcp.sh']).decode()
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 420, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 501, in run
          with Popen(*popenargs, **kwargs) as process:
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 969, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1438, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

What should I do to fix this?

**Comment by Miffyli** [comment]
Hey, I recommend asking MineRL questions in the MineRL repository or the [MineRL Discord](https://discord.com/invite/BT9uegr) server; this place is more for the VPT specific questions :).

But, based on what is in the log, check that you have `bash` command available. If that does not help, please come to the Discord for more interactive support.

**Comment by brandonhoughton** [comment]
Closing this as MineRL issues should be raised there
